drop table ann_online_nov_2023_april_2024;
Create table ann_online_nov_2023_april_2024 AS
SELECT
    ann.reference,
    ann.date_snapshot,
    ann.first_online_date,
    ann.vehicle_id,
    ann.owner_correlation_id,
    ann.initial_price,
    ann.vehicle_gearbox,
    ann.vehicle_co2,
    ann.vehicle_make,
    ann.vehicle_external_color,
    ann.vehicle_energy,
    ann.vehicle_first_hand,
    ann.price,
    ann.vehicle_year,
    ann.zip_code,
    ann.vehicle_model,
    ann.pictures_data_count_valid_photosphere,
    ann.pictures_data_count_valid,
    ann.autoviza_display,
    ann.vehicle_doors,
    ann.vehicle_commercial_name,
    ann.vehicle_internal_color,
    ann.vehicle_power_din,
    ann.vehicle_version,
    ann.vehicle_category,
    ann.vehicle_rated_horse_power,
    ann.vehicle_cubic,
    ann.manufacturer_warranty_duration,
    ann.vehicle_trunk_volume,
    ann.pictures_data_count_valid360_exterieur,
    ann.vehicle_length,
    ann.vehicle_height,
    ann.vehicle_weight,
    ann.good_deal_badge,
    ann.mileage_badge,
    ann.vehicle_brut_quotation,
    ann.good_deal_rate,
    ann.vehicle_refined_quotation,
    ann.vehicle_mileage,
    ann.vehicle_average_mileage,
    ann.vehicle_seats,
    ann.vehicle_pollution_norm,
    ann.vehicle_crit_air,
    ann.vehicle_owners,
    ann.pictures_data_count,
    ann.vehicle_reliability_index,
    ann.customer_type,
    ann.mileage_badge_value,
    ann.good_deal_badge_value,
    ann.network_warranty_duration,
    ann.constructor_warranty_end_date,
    ann.vehicle_condition,
    ann.vehicle_motorization,
    ann.vehicle_trim_level
FROM "dwhstats"."dwh_stats"."dim_annonce_lc_snapshots" ann
WHERE ann.f_status_online = TRUE  
AND CONCAT(CONCAT(CONCAT(CONCAT(ann.year, '-'), ann.month), '-'), ann.day) = CAST(DATEADD(DAY,1,ann.first_online_date) as DATE)
AND CONCAT(CONCAT(CONCAT(CONCAT(ann.year, '-'), ann.month), '-'), ann.day) BETWEEN '2023-11-01' AND '2024-05-16'
order by ann.date_snapshot, ann.reference asc